// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	models "my-test-app/models"

	mock "github.com/stretchr/testify/mock"
)

// GetOneUserer is an autogenerated mock type for the GetOneUserer type
type GetOneUserer struct {
	mock.Mock
}

// GetUser provides a mock function with given fields: _a0
func (_m *GetOneUserer) GetUser(_a0 int) (models.User, error) {
	ret := _m.Called(_a0)

	var r0 models.User
	if rf, ok := ret.Get(0).(func(int) models.User); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(models.User)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
